# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := Hc595Demo
ARDUINO_LIBS := EpoxyMockDigitalWriteFast AceCommon AceSegment AceSPI
include ../../../EpoxyDuino/EpoxyDuino.mk
