# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := Hc595InterruptDemo
ARDUINO_LIBS := EpoxyMockDigitalWriteFast EpoxyMockTimerOne AceCommon \
	AceSegment AceSPI
include ../../../EpoxyDuino/EpoxyDuino.mk
