# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := ModulatingDemo
ARDUINO_LIBS := EpoxyMockDigitalWriteFast AceSegment AceCommon AceSPI
include ../../../EpoxyDuino/EpoxyDuino.mk
