pipeline {
    agent { label 'master' }
    environment {
        AUNITER_ARDUINO_BINARY = '/var/lib/jenkins/arduino-1.8.5/arduino'
    }
    stages {
        stage('Setup') {
            steps {
                dir('AUniter') {
                    git url: 'https://github.com/bxparks/AUniter',
                        branch: 'develop'
                }
                dir('libraries/AUnit') {
                    git url: 'https://github.com/bxparks/AUnit',
                        branch: 'develop'
                }
                dir('libraries/AceButton') {
                    git url: 'https://github.com/bxparks/AceButton',
                        branch: 'develop'
                }
                dir('libraries/digitalWriteFast') {
                    git url: 'https://github.com/NicksonYap/digitalWriteFast',
                        branch: 'master'
                }
            }
        }
        stage('Example') {
            steps {
                sh "AUniter/auniter.sh \
                    --pref sketchbook.path=$WORKSPACE \
                    --config libraries/AceSegment/tests/auniter.conf \
                    --boards nano:/dev/ttyUSB0 \
                    --verify \
                    libraries/AceSegment/examples/*"
            }
        }
        stage('Test') {
            steps {
                sh "AUniter/auniter.sh \
                    --pref sketchbook.path=$WORKSPACE \
                    --config libraries/AceSegment/tests/auniter.conf \
                    --boards nano:/dev/ttyUSB0 \
                    --test \
                    libraries/AceSegment/tests/*Test"
            }
        }
    }
}
