// See https://github.com/bxparks/AUniter/tree/develop/jenkins for
// a description of AUniter integration with Jenkins.
//
// The following variables are used:
//
//  * AUNITER_ARDUINO_BINARY - defined in the Jenkins system configuration
//  * WORKSPACE - automatically filled in by Jenkins
//  * BOARDS - defined in the "This project is parameterized" section of the
//    Jenkins Pipeline configuration
//
pipeline {
    agent { label 'master' }
    stages {
        stage('Setup') {
            steps {
                dir('AUniter') {
                    git url: 'https://github.com/bxparks/AUniter',
                        branch: 'develop'
                }
                dir('libraries/AUnit') {
                    git url: 'https://github.com/bxparks/AUnit',
                        branch: 'develop'
                }
                dir('libraries/AceButton') {
                    git url: 'https://github.com/bxparks/AceButton',
                        branch: 'develop'
                }
                dir('libraries/digitalWriteFast') {
                    git url: 'https://github.com/NicksonYap/digitalWriteFast',
                        branch: 'master'
                }
            }
        }
        stage('Verify Examples') {
            steps {
                sh "AUniter/auniter.sh --verify \
                    --pref sketchbook.path=$WORKSPACE \
                    --config libraries/AceSegment/tests/auniter.conf \
                    --boards $BOARDS \
                    libraries/AceSegment/examples/*"
            }
        }
        stage('Verify Tests') {
            steps {
                sh "AUniter/auniter.sh --verify \
                    --pref sketchbook.path=$WORKSPACE \
                    --config libraries/AceSegment/tests/auniter.conf \
                    --boards $BOARDS \
                    libraries/AceSegment/tests/*Test"
            }
        }
        stage('Test') {
            steps {
                sh "AUniter/auniter.sh --test \
                    --skip_if_no_port \
                    --pref sketchbook.path=$WORKSPACE \
                    --config libraries/AceSegment/tests/auniter.conf \
                    --boards $BOARDS \
                    libraries/AceSegment/tests/*Test"
            }
        }
    }
    post {
        failure {
            script {
                if (env.BADGE_BUCKET?.trim()) {
                    sh "AUniter/badgeservice/set-badge-status.sh \
                        $BADGE_BUCKET AceSegment FAILED"
                }
            }
        }
        success {
            script {
                if (env.BADGE_BUCKET?.trim()) {
                    sh "AUniter/badgeservice/set-badge-status.sh \
                        $BADGE_BUCKET AceSegment PASSED"
                }
            }
        }
    }
}
