# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := HelloHt16k33
ARDUINO_LIBS := AceCommon AceSegment AceWire
include ../../../EpoxyDuino/EpoxyDuino.mk
