# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := HelloMax7219
ARDUINO_LIBS := AceCommon AceSegment AceSPI
include ../../../EpoxyDuino/EpoxyDuino.mk
