# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := HelloTm1638
ARDUINO_LIBS := AceCommon AceSegment AceTMI
include ../../../EpoxyDuino/EpoxyDuino.mk
