# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := AutoBenchmark
ARDUINO_LIBS := AceSegment AceButton AUnit
include ../../../EpoxyDuino/EpoxyDuino.mk
