# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := AceSegmentDemo
ARDUINO_LIBS := EpoxyMockDigitalWriteFast EpoxyMockTimerOne \
	AceSegment AceButton AUnit AceCommon
include ../../../EpoxyDuino/EpoxyDuino.mk
