# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := ScanningModuleTest
ARDUINO_LIBS := AUnit AceCommon AceSegment
include ../../../EpoxyDuino/EpoxyDuino.mk
