# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := Tm1638AnodeDemo
ARDUINO_LIBS := EpoxyMockDigitalWriteFast AceCommon AceSegment AceTMI
include ../../../EpoxyDuino/EpoxyDuino.mk
