# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := AceSegmentTester
ARDUINO_LIBS := EpoxyMockDigitalWriteFast EpoxyMockTimerOne \
	AceSegment AceButton AUnit AceCommon AceSPI AceTMI AceWire
include ../../../EpoxyDuino/EpoxyDuino.mk
